name: Create VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Vagrant
      run: |
        sudo apt-get update
        sudo apt-get install vagrant -y

    - name: Create VM
      run: |
        vagrant init ubuntu/bionic64
        vagrant up
